<template>
    <svg
        aria-hidden="true"
        class="absolute top-0 hidden lg:block"
        fill="none"
        height="384"
        viewBox="0 0 404 384"
        width="404"
    >
        <defs>
            <pattern
                id="de316486-4a29-4312-bdfc-fbce2132a2c1"
                height="20"
                patternUnits="userSpaceOnUse"
                width="20"
                x="0"
                y="0"
            >
                <rect
                    class="text-primary-700"
                    fill="currentColor"
                    height="4"
                    width="4"
                    x="0"
                    y="0"
                />
            </pattern>
        </defs>
        <rect
            fill="url(#de316486-4a29-4312-bdfc-fbce2132a2c1)"
            height="384"
            width="404"
        />
    </svg>
</template>
